[package]
authors = ["Hunter Praska <hunter@wiggin-labs.com>"]
name = "valentine"
version = "0.1.0"

[dependencies]
bart = "0.1.4"
bart_derive = "0.1.4"
base64 = "0.6.0"
bcrypt = "0.1.3"
clap = "2.26.1"
git2 = "0.6.8"
log = "0.3.8"
pulldown-cmark = "0.1.0"
quick-error = "1.2.1"
r2d2 = "0.7.4"
r2d2-diesel = "0.16.0"
rand = "0.3.16"
serde = "1.0.14"
serde_derive = "1.0.14"
serde_json = "1.0.3"
sha2 = "0.6.0"
slog = "2.0.11"
slog-scope = "4.0.0"
slog-stdlog = "3.0.2"
slog-term = "2.2.0"
time = "0.1.38"
toml = "0.4.5"

[dependencies.chrono]
features = ["serde"]
version = "0.4.0"

[dependencies.diesel]
features = [
    "postgres",
    "chrono",
]
version = "0.16.0"

[dependencies.diesel_codegen]
features = ["postgres"]
version = "0.16.0"

[dependencies.explode]
git = "https://git.hunterpraska.com/hunter/explode"

[dependencies.hayaku]
git = "https://git.hunterpraska.com/hayaku/hayaku"
