[package]
authors = ["Hunter Praska <hunter@wiggin-labs.com>"]
name = "valentine"
version = "0.1.0"

[dependencies]
bart = "0.1.4"
bart_derive = "0.1.4"
base64 = "0.6.0"
bcrypt = "0.1.3"
clap = "2.24.2"
git2 = "0.6.4"
log = "0.3.7"
pulldown-cmark = "0.0.15"
quick-error = "1.2.0"
r2d2 = "0.7.2"
r2d2-diesel = "0.14.0"
rand = "0.3.15"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
sha2 = "0.6.0"
slog = "2.0.6"
slog-scope = "4.0.0"
slog-stdlog = "3.0.2"
slog-term = "2.0.1"
time = "0.1.37"
toml = "0.4.1"

[dependencies.chrono]
features = ["serde"]
version = "0.4"

[dependencies.diesel]
features = ["postgres", "chrono"]
version = "0.14.0"

[dependencies.diesel_codegen]
features = ["postgres"]
version = "0.14.0"

[dependencies.explode]
git = "https://git.hunterpraska.com/hunter/explode"
#path = "../explode"

[dependencies.hayaku]
git = "https://git.hunterpraska.com/hayaku/hayaku"
