[package]
authors = ["nokaa <nokaa@cock.li>"]
name = "wanker"
version = "0.1.0"

[dependencies]
bcrypt = "0.1.3"
dotenv = "0.10.0"
env_logger = "0.4.2"
git2 = "0.6.4"
log = "0.3.7"
quick-error = "1.2.0"
r2d2 = "0.7.2"
r2d2_postgres = "0.12.0"
rand = "0.3.15"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
time = "0.1.37"

[dependencies.bart]
git = "https://github.com/maghoff/bart"

[dependencies.bart_derive]
git = "https://github.com/maghoff/bart"

[dependencies.chrono]
features = ["serde"]
version = "0.3"

[dependencies.hayaku]
#git = "https://git.nokaa.moe/hayaku/hayaku"
path = "../hayaku"

[dependencies.postgres]
features = ["with-chrono"]
version = "0.14"
