[package]
authors = ["nokaa <nokaa@cock.li>"]
name = "valentine"
version = "0.1.0"

[dependencies]
base64 = "0.6.0"
bcrypt = "0.1.3"
clap = "2.24.2"
git2 = "0.6.4"
log = "0.3.7"
quick-error = "1.2.0"
r2d2 = "0.7.2"
r2d2_postgres = "0.12.0"
rand = "0.3.15"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
sha2 = "0.6.0"
slog = "2.0.6"
slog-scope = "4.0.0"
slog-stdlog = "3.0.2"
slog-term = "2.0.1"
time = "0.1.37"
toml = "0.4.1"

[dependencies.bart]
git = "https://github.com/maghoff/bart"

[dependencies.bart_derive]
git = "https://github.com/maghoff/bart"

[dependencies.chrono]
features = ["serde"]
version = "0.4"

[dependencies.hayaku]
git = "https://git.nokaa.moe/hayaku/hayaku"

[dependencies.postgres]
features = ["with-chrono", "with-uuid"]
version = "0.14"

[dependencies.uuid]
features = ["v4", "serde"]
version = "0.5.0"
