CREATE TABLE IF NOT EXISTS users (
    id INTEGER PRIMARY KEY,
    username VARCHAR NOT NULL UNIQUE,
    email VARCHAR NOT NULL,
    password VARCHAR NOT NULL,
    num_repos INTEGER NOT NULL,
    is_admin BOOLEAN NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS public_keys (
    id INTEGER PRIMARY KEY,
    owner INTEGER REFERENCES users (id) ON DELETE CASCADE,
    name VARCHAR NOT NULL,
    fingerprint VARCHAR NOT NULL,
    content TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS repos (
    id INTEGER PRIMARY KEY,
    name VARCHAR NOT NULL,
    description VARCHAR NOT NULL,
    owner INTEGER REFERENCES users (id) ON DELETE CASCADE,
    private BOOLEAN NOT NULL,
    last_updated TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    unique (name, owner)
);
